### ISSUE TITLE
NO windows wheels??

### ISSUE THREAD

**Issue by BBC-Esq** [TileDB-Inc/TileDB-Vector-Search#292]
I was wondering why you stopped making windows wheels after version 0.0.21?  This makes it difficult to simply follow the installation instructions on langchain when it says to merely ```pip install tiledb-vector-search```.  For example, running that command gives this error message:

![image](https://github.com/TileDB-Inc/TileDB-Vector-Search/assets/108230321/9b171e2a-463a-4814-a480-6edea6b67a5c)

However, running ```pip install tiledb-vector-search==0.0.21``` does work...

**Comment by ihnorton** [comment]
Hi @BBC-Esq, thanks for opening the issue. We've re-enabled windows builds/wheels recently (https://github.com/TileDB-Inc/TileDB-Vector-Search/pull/250) but it looks like the wheel build didn't go through. We'll take a look ASAP.

**Comment by dudoslav** [comment]
Hello @BBC-Esq,
we just released a new version: `0.1.1` with Windows wheels: https://pypi.org/project/tiledb-vector-search/#files

Please let us know if you have any issues and we’ll reopen.

**Comment by BBC-Esq** [comment]
Will give it a shot!
