### ISSUE TITLE
STRANGE error message but DB seems to have been created

### ISSUE THREAD

**Issue by BBC-Esq** [TileDB-Inc/TileDB-Vector-Search#293]
I keep receiving the following error message whenever I create a DB:

```
UserWarning: You must first login before you can run commands. Please run tiledb.cloud.login.
  warnings.warn(
```

I discovered that this error stems from ```config.py``` here:

```
    if (token is None or token == "") and (username is None or username == ""):
        warnings.warn(
            "You must first login before you can run commands."
            " Please run tiledb.cloud.login."
        )
        logged_in = False
```

However, I am NOT attempting to use some cloud bases service.  Rather, I'm creating a local database with this code snippet:

```
    db = TileDB.from_embeddings(
        text_embeddings=text_embeddings,
        embedding=HuggingFaceEmbeddings(),
        allow_dangerous_deserialization=True,
        index_uri=index_uri,
        metric="euclidean",
        index_type="FLAT"
    )
```

The DB SEEMS to be successfully created although I haven't tried actually searching it yet:

![image](https://github.com/TileDB-Inc/TileDB-Vector-Search/assets/108230321/ca56eb6a-0cd4-461e-a951-597d319f2c8e)

QUESTIONS:

1) Is the "warning" message merely informational in that it won't stop me from creating a DB and/or searching it?

2)  If so, is there a way to suppress it?

Using Windows 10.  Sentence-transformers==2.5.0, tiledb-vector-search==0.0.21 (since you don't have recent windows wheels), let me know if you need any additional info...

**Comment by ihnorton** [comment]
> Is the "warning" message merely informational in that it won't stop me from creating a DB and/or searching it?

Correct

> If so, is there a way to suppress it?

I believe the only way right now is to suppress all python warnings, but I've added an internal issue [sc-43725] to fix this, and we'll keep this story open until it's fixed.

Thanks for opening the issue.

**Comment by BBC-Esq** [comment]
Closed as not significant and I'll resolve it but thanks for answering.
