### ISSUE TITLE
Is the python tile db required OR NOT?

### ISSUE THREAD

**Issue by BBC-Esq** [TileDB-Inc/TileDB-Vector-Search#294]
In a previous version of my program, before you updated the Windows wheels, it took me a long time to get it working.  What I discovered is that I was required to install the python library here BEFORE (AND ONLY BEFORE) this library:

tiledb==0.27.0

pypi is here: https://pypi.org/project/tiledb/

This confused me because the Langchain instructions said that I only needed to install TileDB-Vector-Search...

Now, since you released version 0.1.1 I SOLELY installed TileDB-Vector-Search and my program is running fine now...no need to also install "tiledb".

Any idea why this is?  Am I missing something and tiledb is still required?  Perhaps I'm just not noticing it yet because I haven't tested any/all functionalities of my program that might rely on TileDB?

What's officially required - any and all libraries - to make it work with Langchain's framework?  Thanks, love the project.  Just switched from using ChromaDB for the last 8 months.

**Comment by ihnorton** [comment]
Hi @BBC-Esq,

> What's officially required - any and all libraries - to make it work with Langchain's framework

The `tiledb` PyPI package is indeed required. All direct dependencies are listed here:

https://github.com/TileDB-Inc/TileDB-Vector-Search/blob/main/pyproject.toml#L20-L25

(there are also indirect dependencies on numpy and other libraries via `tiledb` and `scikit-learn` -- all of which should be installed automatically along with `pip install tiledb-vector-search`)

The pyproject.toml looks correct over several prior versions, so I'm not quite sure what to make of your experience with the prior wheel version. Glad it is working now!

**Comment by BBC-Esq** [comment]
Asked and answered.
