### ISSUE TITLE
Listing TileDB-Vector-Search as an example on quartodoc

### ISSUE THREAD

**Issue by machow** [TileDB-Inc/TileDB-Vector-Search#77]
Hello! I noticed that you are currently using quartodoc to generate your python API reference. Do you mind if I link to your project from quartodoc?

Also, please let me know if you run into any issues at all! I'm happy to debug / add useful features!

**Comment by Shelnutt2** [comment]
Hi @machow , we do not mind you linking at all.  We have used quartodoc for a few projects and have been loving it so far! We'll be sure to let you know if we have any feature requests.
